import type { Video } from '@/lib/types';

export const VIDEOS: Video[] = [
  {
    id: 'prompt-engineering',
    title: 'Prompt engineering, explained',
    description: 'Learn a practical prompt formula from Jeff Su to make ChatGPT instructions clearer and more useful.',
    category: 'Artificial Intelligence',
    difficulty: 'Beginner',
    duration: 9,
    skill: 'Prompt design',
    youtubeVideoId: 'jC4v5AS4RIM',
    instructor: 'Jeff Su',
    thumbnail: 'from-violet-500 to-indigo-600',
  },
  {
    id: 'python-fundamentals',
    title: 'Python fundamentals in one lesson',
    description: 'Learn Python variables, data types, and comments in this beginner lesson from WsCube Tech.',
    category: 'Python',
    difficulty: 'Beginner',
    duration: 24,
    skill: 'Python basics',
    youtubeVideoId: 'TKaLhiFTAM8',
    instructor: 'WsCube Tech',
    thumbnail: 'from-sky-500 to-blue-700',
  },
  {
    id: 'salesforce-flows',
    title: 'Automate a process with Salesforce Flows',
    description: 'Get an introduction to Salesforce Flow Builder and no-code automation.',
    category: 'Salesforce',
    difficulty: 'Intermediate',
    duration: 5,
    skill: 'Flow Builder',
    youtubeVideoId: 'aOG4R36EZWI',
    instructor: 'Salesforce Help Club',
    thumbnail: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'data-storytelling',
    title: 'Make your data tell a story',
    description: 'Learn three practical steps for communicating data and numbers as a clear story.',
    category: 'Data Science',
    difficulty: 'Beginner',
    duration: 6,
    skill: 'Data visualization',
    youtubeVideoId: 'zklM_KnNloI',
    instructor: 'Word Cortex with Anita',
    thumbnail: 'from-amber-500 to-orange-600',
  },
  {
    id: 'cloud-basics',
    title: 'Cloud computing: the essentials',
    description: 'A concise introduction to what cloud computing is and how it works.',
    category: 'Cloud Computing',
    difficulty: 'Beginner',
    duration: 7,
    skill: 'Cloud foundations',
    youtubeVideoId: 'M988_fsOSWo',
    instructor: 'Simplilearn',
    thumbnail: 'from-emerald-500 to-green-700',
  },
];
