import type { Video } from '@/lib/types';

export const VIDEOS: Video[] = [
  {
    id: 'prompt-engineering',
    title: 'Prompt engineering, explained',
    description: 'Learn to write clear, effective prompts and get more useful results from AI.',
    category: 'Artificial Intelligence',
    difficulty: 'Beginner',
    duration: 18,
    skill: 'Prompt design',
    instructor: 'Maya Chen',
    thumbnail: 'from-violet-500 to-indigo-600',
  },
  {
    id: 'python-fundamentals',
    title: 'Python fundamentals in one lesson',
    description: 'Build a solid foundation in variables, data types, and your first Python functions.',
    category: 'Python',
    difficulty: 'Beginner',
    duration: 24,
    skill: 'Python basics',
    instructor: 'Alex Rivera',
    thumbnail: 'from-sky-500 to-blue-700',
  },
  {
    id: 'salesforce-flows',
    title: 'Automate a process with Salesforce Flows',
    description: 'Turn a repetitive task into a simple, reliable no-code automation.',
    category: 'Salesforce',
    difficulty: 'Intermediate',
    duration: 32,
    skill: 'Flow Builder',
    instructor: 'Jordan Lee',
    thumbnail: 'from-cyan-500 to-teal-600',
  },
  {
    id: 'data-storytelling',
    title: 'Make your data tell a story',
    description: 'Choose the right chart and communicate the insight behind your numbers.',
    category: 'Data Science',
    difficulty: 'Beginner',
    duration: 16,
    skill: 'Data visualization',
    instructor: 'Sam Patel',
    thumbnail: 'from-amber-500 to-orange-600',
  },
  {
    id: 'cloud-basics',
    title: 'Cloud computing: the essentials',
    description: 'Understand the building blocks behind modern cloud platforms.',
    category: 'Cloud Computing',
    difficulty: 'Beginner',
    duration: 21,
    skill: 'Cloud foundations',
    instructor: 'Taylor Brooks',
    thumbnail: 'from-emerald-500 to-green-700',
  },
];
